FROM golang:1.25-alpine AS builder
WORKDIR /build
RUN apk add --no-cache git ca-certificates
COPY go.mod go.sum ./
RUN go mod download
COPY . .
FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=builder /build /build
WORKDIR /build
ENTRYPOINT ["go", "test", "-v", "-tags=integration_real", "-count=1"]
